In [2]:
# numpy  -  exercise

# 1.  Represent the above data in a 10x2 array. In each row, the first element should contain day number and second element should contain steps walked. 
#
# Given data: day numbers and steps walked

import numpy as np
day_numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
steps_walked = np.array([6012, 7079, 6886, 7230, 4598, 5564, 6971, 7763, 8032, 9569])

# Create a 10x2 array
data_array = np.column_stack((day_numbers, steps_walked))
print(data_array)

# anoher simpler way
data_array1 = np.array([
    [1, 6012],
    [2, 7079],
    [3, 6886],
    [4, 7230],
    [5, 4598],
    [6, 5564],
    [7, 6971],
    [8, 7763],
    [9, 8032],
    [10, 9569]
])
print(data_array1)

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]
[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]


In [3]:
# 2 Lee notices that the tracker’s battery dies every day at 7 pm. 
# Lee discovers that on an average, he walks 2000 steps every day after 7 pm. 
# Perform an appropriate operation on your array to add 2000 steps to all the observations.


# Adding 2000 steps to all the observations after 7 pm
data_array[:, 1] += 2000

print(data_array)

[[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


In [4]:
# 3 Write a program that returns the steps walked if the steps walked are more than 9000.

# Function to filter steps walked more than 9000
def steps_more_than_9000(data):
    return data[data[:, 1] > 9000]

# Get the steps walked more than 9000
steps_walked_more_than_9000 = steps_more_than_9000(data_array)
print(steps_walked_more_than_9000)

steps_walked_more_than_9000 = data_array[data_array[:, 1] > 9000]
print(steps_walked_more_than_9000)


[[    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]
[[    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


In [5]:
#4 Print an array containing steps walked in sorted order. 
sorted_array = data_array[data_array[:, 1].argsort()]

print(sorted_array)

[[    5  6598]
 [    6  7564]
 [    1  8012]
 [    3  8886]
 [    7  8971]
 [    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


In [6]:
sorted_array_descending = data_array[data_array[:, 1].argsort()[::-1]]
print(sorted_array_descending)


[[   10 11569]
 [    9 10032]
 [    8  9763]
 [    4  9230]
 [    2  9079]
 [    7  8971]
 [    3  8886]
 [    1  8012]
 [    6  7564]
 [    5  6598]]
