# Vector
# A vector is an ordered collection of scalars. It can be represented in two forms:

# Column vector: Contains n rows and 1 column
# Row vector: Contains 1 row and n columns
# The number of scalars in a vector is called its dimension or order. 

# Example: A column vector 'u' of dimension 2 is illustrated below:
# u = [4
       3]
# v = [ 4  -1 2]

#Example: A row vector 'v' of dimension 3 is illustrated below:



In [1]:
# importing required library (numpy as np)
import numpy as np
# creating a column vector with 2 rows and 1 column using np.array() function
col_vec = np.array([[4],[3]])
print ("A column vector\n",col_vec)
# printing the shape of the vector
print("Shape of vector=",col_vec.shape)


A column vector
 [[4]
 [3]]
Shape of vector= (2, 1)


In [2]:
# importing required library (numpy as np)
import numpy as np
# creating a row vector with 1 row and 3 columns using np.array() function
row_vec = np.array([[4,-1,2]])
print("A row vector\n",row_vec)
# printing the shape of the vector
print("Shape of vector=",row_vec.shape)


A row vector
 [[ 4 -1  2]]
Shape of vector= (1, 3)


In [3]:
# importing required library (numpy as np)
import numpy as np
#Illustrating a Zero row vector of dimension 3 using np.array() function
zero_vector_1=np.array([0,0,0])
print(zero_vector_1)
#Illustrating a Zero row vector of dimension 3 using np.zeros() function
zero_vector_2=np.zeros(3)
print(zero_vector_2)
#Illustrating a Zero column vector of dimension 3 using np.zeros() and reshape() function
zero_vector_3=np.zeros(3).reshape(3,-1)
print(zero_vector_3)


[0 0 0]
[0. 0. 0.]
[[0.]
 [0.]
 [0.]]


In [4]:
# importing required library (numpy as np)
import numpy as np
#Illustrating a One vector of dimension 3 using np.array() function
one_vector_1=np.array([1,1,1])
print(one_vector_1)
#Illustrating a One vector of dimension 3 using np.ones() function
one_vector_2=np.ones(3)
print(one_vector_2)
#Illustrating a column vector of ones of dimension 3 using np.ones() and reshape() function 
one_vector_3=np.ones(3).reshape(3,-1)
print(one_vector_3)


[1 1 1]
[1. 1. 1.]
[[1.]
 [1.]
 [1.]]
