In [1]:
# importing required libraries (numpy as np)
import numpy as np
# Creating matrices of various dimension using np.array() function
matrix_2x2 = np.array([[1, 2], 
                       [3, 4]])
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [8, 9, 10]])
print("2x2 Matrix\n",matrix_2x2,"\nshape of matrix -> ",matrix_2x2.shape)
print("\n3x3 Matrix\n",matrix_3x3,"\nshape of matrix -> ",matrix_3x3.shape)


2x2 Matrix
 [[1 2]
 [3 4]] 
shape of matrix ->  (2, 2)

3x3 Matrix
 [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]] 
shape of matrix ->  (3, 3)


# Types of Matrices
# Matrices can be categorized on the basis of the value of their elements, position of elements,  number of rows and columns, etc. as follows:

# Diagonal matrix
# Identity matrix
# Symmetric matrix
# Triangular matrix

In [2]:
# Diagonal Matrix

# importing required libraries (numpy as np)
import numpy as np
# Creating a diagonal matrix with diagonal elements as (1,3,2)
diagonal_matrix = np.diag((1,3,2))
print(diagonal_matrix)
# Creating a diagonal matrix with a range of values
matrix_range= np.diag(np.arange(1,6,2))
print(matrix_range)


[[1 0 0]
 [0 3 0]
 [0 0 2]]
[[1 0 0]
 [0 3 0]
 [0 0 5]]


# Identity Matrix
# An identity matrix is a square matrix of dimensions (n, n) having '1' across its main diagonal and '0' everywhere else. It is usually represented as 'In'

# Example: The matrix shown below illustrates a (3, 3) Identity matrix.



In [3]:
# importing required libraries (numpy as np)
import numpy as np
#Creating an Identity matrix of size 2 using np.identity() function
identity_matrix_1 = np.identity(2)
print("Identity_matrix 1\n",identity_matrix_1)
#Creating an Identity matrix of size 3 using np.eye() fucntion
identity_matrix_2 = np.eye(3)
print("\nIdentity_matrix 2\n",identity_matrix_2)


Identity_matrix 1
 [[1. 0.]
 [0. 1.]]

Identity_matrix 2
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Symmetric Matrix
# A square matrix A of dimension (n, n) is symmetric, if A = AT i.e.  the matrix A is the same as its transpose.

In [5]:
# importing required libraries (numpy as np)
import numpy as np
#Creating matrix A
A = np.array([[2,3,1],
            [3,4,-1],
            [1,-1,1]])
print("A:\n" , A)
# Finding the Transpose of the matrix
transposed_matrix = A.transpose()
print("Transpose of A:\n" , transposed_matrix)
#Comparing each element of both matrices (returns a matrix of boolean compared values) and saving it in a variable comparison
comparison = (A == transposed_matrix)
#Checking if all the elements in the matrix comparision is true
equal_arrays = comparison.all()
print(equal_arrays)


A:
 [[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
Transpose of A:
 [[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
True


# Triangular Matrix
# A triangular matrix can be either a lower triangular or an upper triangular matrix.



In [8]:
# importing required libraries (numpy as np)
import numpy as np
#Creating a lower triangular matrix
lower_triangular_matrix_1 = np.tril([[1,2,3],
                               [4,5,6],
                               [7,8,9]])
print("Lower triangular matrix\n",lower_triangular_matrix_1)


Lower triangular matrix
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


In [9]:
# importing required libraries (numpy as np)
import numpy as np
#Creating a Upper triangular matrix
upper_triangular_matrix_1 = np.triu([[1,2,3],
                               [4,5,6],
                               [7,8,9]])
print("Upper triangular matrix\n",upper_triangular_matrix_1)


Upper triangular matrix
 [[1 2 3]
 [0 5 6]
 [0 0 9]]
