# Find the solution of the following System of Linear Equations using Cramer’s Rule.
2x + 3y + 2z = 1   
x + 3z = 2   
2x + 2y + 2z = 3   

In [7]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, 3, 2],
              [1, 0, 3],
              [2, 2, 2]])

# Constant matrix B
B = np.array([1, 2, 3])
print(f'A = {A}')
print(f'B = {B}')
# Calculate the determinant of A
detA = np.linalg.det(A)

# Calculate the determinants of Ax, Ay, and Az
Ax = A.copy()
Ax[:, 0] = B
print(f'Ax = {Ax}')
detAx = np.linalg.det(Ax)

Ay = A.copy()
Ay[:, 1] = B
detAy = np.linalg.det(Ay)

Az = A.copy()
Az[:, 2] = B
detAz = np.linalg.det(Az)

# Calculate the solutions for x, y, and z
x = detAx / detA
y = detAy / detA
z = detAz / detA

print("Solution:")
print(f"x = {x:.2f}, y = {y:.2f}, z = {z:.2f}")


A = [[2 3 2]
 [1 0 3]
 [2 2 2]]
B = [1 2 3]
Ax = [[1 3 2]
 [2 0 3]
 [3 2 2]]
Solution:
x = 4.25, y = -2.00, z = -0.75


# Exercise 2
# Find the solution of the following System of Equations using Gaussian Elimination and Gauss Jordan method.

12x1 + x2  = 18    
7x1  -  8x2 = 32


# 1 : Gaussian Elimination:

In [9]:
import numpy as np

# Coefficient matrix A
A = np.array([[12, 1],
              [7, -8]], dtype=float)  # Specify dtype=float

# Constant matrix B
B = np.array([18, 32], dtype=float)  # Specify dtype=float

# Augmented matrix [A|B]
augmented_matrix = np.column_stack((A, B))

# Perform Gaussian Elimination
n = augmented_matrix.shape[0]  # Number of equations

for i in range(n):
    # Make the diagonal element 1
    divisor = augmented_matrix[i, i]
    augmented_matrix[i, :] /= divisor

    # Eliminate other elements in the current column
    for j in range(n):
        if i != j:
            factor = augmented_matrix[j, i]
            augmented_matrix[j, :] -= factor * augmented_matrix[i, :]

# Back-substitute to find the values of x1 and x2
x2 = augmented_matrix[1, -1]
x1 = augmented_matrix[0, -1] - augmented_matrix[0, 1] * x2

print("Solution using Gaussian Elimination:")
print(f"x1 = {x1:.2f}, x2 = {x2:.2f}")


Solution using Gaussian Elimination:
x1 = 1.71, x2 = -2.50


#  Gauss-Jordan method in Python:

In [11]:
import numpy as np

# Coefficient matrix A
A = np.array([[12, 1],
              [7, -8]], dtype=float)  # Specify dtype=float

# Constant matrix B
B = np.array([18, 32], dtype=float)  # Specify dtype=float

# Augmented matrix [A|B]
augmented_matrix = np.column_stack((A, B))

# Perform Gauss-Jordan method
n = augmented_matrix.shape[0]  # Number of equations

for i in range(n):
    # Make the diagonal element 1
    divisor = augmented_matrix[i, i]
    augmented_matrix[i, :] /= divisor

    # Eliminate other elements in the current column
    for j in range(n):
        if i != j:
            factor = augmented_matrix[j, i]
            augmented_matrix[j, :] -= factor * augmented_matrix[i, :]

# The last column contains the solutions for x1 and x2
solutions = augmented_matrix[:, -1]

x1 = solutions[0]
x2 = solutions[1]

print("\nSolution using Gauss-Jordan method:")
print(f"x1 = {x1:.2f}, x2 = {x2:.2f}")



Solution using Gauss-Jordan method:
x1 = 1.71, x2 = -2.50
