Create a square matrix A of order 3. Solve the following:
    1. Convert A to an upper triangular matrix B

In [1]:
import numpy as np

# Step 1: Create a square matrix A of order 3
A = np.array([[2, 4, 1],
              [6, 2, 3],
              [1, 5, 4]])

print("Matrix A:")
print(A)

# Step 2: Convert A to an upper triangular matrix B
B = np.triu(A)

print("\nUpper triangular matrix B:")
print(B)


Matrix A:
[[2 4 1]
 [6 2 3]
 [1 5 4]]

Upper triangular matrix B:
[[2 4 1]
 [0 2 3]
 [0 0 4]]


2. Convert B to an upper triangular matrix C

In [2]:
C = np.tril(B)
print("\nLower triangular matrix C:")
print(C)


Lower triangular matrix C:
[[2 0 0]
 [0 2 0]
 [0 0 4]]


Find the transpose of matrix C

In [3]:
# Find the transpose of matrix C
transposed_matrix = C.transpose()
print("\ntransposed_matrix:")
print(transposed_matrix)


transposed_matrix:
[[2 0 0]
 [0 2 0]
 [0 0 4]]


In [4]:
# Check whether matrix C is a diagonal matrix
import numpy as np

# Step 1: Create the matrix C
C = np.array([[2, 0, 0],
              [0, 2, 0],
              [0, 0, 4]])

# Step 2: Check if C is a diagonal matrix
is_diagonal = np.all(C == np.diag(np.diagonal(C)))

if is_diagonal:
    print("Matrix C is a diagonal matrix.")
else:
    print("Matrix C is not a diagonal matrix.")


Matrix C is a diagonal matrix.


In [5]:
# Check whether matrix C is symmetric
import numpy as np

# Define the matrix C
C = np.array([[2, 0, 0],
              [0, 2, 0],
              [0, 0, 4]])

# Check if the matrix is symmetric
is_symmetric = np.array_equal(C, C.T)

if is_symmetric:
    print("Matrix C is symmetric.")
else:
    print("Matrix C is not symmetric.")



Matrix C is symmetric.
